version: '3.7'


services:
  base_image:
    image: ${BASE_IMAGE_TAG:-{{ project_name }}}
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: /bin/bash -c "true"
  web:
    image: ${BASE_IMAGE_TAG:-{{ project_name }}}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env.prod
    volumes:
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/mediafiles
    depends_on:
      - base_image
      - db
    entrypoint: ./entrypoint.sh
    restart: always
  worker:
    image: ${BASE_IMAGE_TAG:-{{ project_name }}}
    env_file:
      - .env.prod
    depends_on:
      - base_image
      - db
      - redis
    command: /bin/bash -c "python manage.py run_huey"
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  redis:
    image: redis:5
    restart: always

volumes:
  postgres_data:
